# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('geoSVR', ['location-service', 'internet', 'wifi', 'applications', 'mesh', 'point-to-point', 'virtual-net-device'])
    module.source = [
        'model/geoSVR-neighbors.cc',
        'model/geoSVR-rqueue.cc',
        'model/geoSVR-packet.cc',
        'model/geoSVR-packet-tag.cc',
        'model/geoSVR.cc',
        'model/geoSVR-map.cc',
        'helper/geoSVR-helper.cc',
        ]

    headers = bld(features=['ns3header'])
    headers.module = 'geoSVR'
    headers.source = [
        'model/geoSVR-neighbors.h',
        'model/geoSVR-rqueue.h',
        'model/geoSVR-packet.h',
        'model/geoSVR-packet-tag.h',
        'model/geoSVR.h',
        'model/geoSVR-map.h',
        'helper/geoSVR-helper.h',
        ]

    
    # bld.ns3_python_bindings()

